# dynamic_title = true

# draw_bold_text_with_bright_colors = true

# import = [
#     "~/.config/alacritty/themes/themes/pencil_light.toml"
# ]
[colors]
[colors.primary]
background = "0xeeeeee"
foreground = "0x444444"
[colors.cursor]
text = "0xeeeeee"
cursor = "0x444444"
[colors.normal]
black = "0xeeeeee"
red = "0xaf0000"
green = "0x008700"
yellow = "0x5f8700"
blue = "0x0087af"
magenta = "0x878787"
cyan = "0x005f87"
white = "0x444444"
[colors.bright]
black = "0xbcbcbc"
red = "0xd70000"
green = "0xd70087"
yellow = "0x8700af"
blue = "0xd75f00"
magenta = "0xd75f00"
cyan = "0x005faf"
white = "0x005f87"

# [colors.bright]
# black = "#928374"
# blue = "#83a598"
# cyan = "#8ec07c"
# green = "#b8bb26"
# magenta = "#d3869b"
# red = "#fb4934"
# white = "#ebdbb2"
# yellow = "#fabd2f"

# [colors.normal]
# black = "#282828"
# blue = "#458588"
# cyan = "#689d6a"
# green = "#98971a"
# magenta = "#b16286"
# red = "#cc241d"
# white= "#eaeaea"
# yellow = "#d79921"

# [colors.primary]
# # background = "#2B2D37"
# background = "#303030"
# foreground = "#eaeaea"

# [colors.selection]
# background = "0xdc3232"
# text = "0xffffff"
# # white= "0xffffff"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 13.5
# use_thin_strokes = false

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

# [font.debug]
# persistent_logging = false

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
#family = "MonoLisa Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
opacity = 0.99

[window.dimensions]
columns = 100
lines = 28

[window.padding]
x = 15
y = 15

[mouse]
# url_launcher = true
# hide_when_typing = false
# scroll = false  # This prevents scrolling to the bottom on copy
